apiVersion: apps/v1
kind: Deployment
metadata:
  name: rosa-namespace-provisioner
  namespace: default
  labels:
    app: rosa-namespace-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rosa-namespace-provisioner
  template:
    metadata:
      labels:
        app: rosa-namespace-provisioner
    spec:
      serviceAccountName: rosa-namespace-provisioner
      containers:
      - name: controller
        image: rosa-namespace-provisioner:latest
        imagePullPolicy: IfNotPresent
        args:
        - --v=2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rosa-namespace-provisioner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rosa-namespace-provisioner
rules:
- apiGroups: ["user.openshift.io"]
  resources: ["groups"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rosa-namespace-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rosa-namespace-provisioner
subjects:
- kind: ServiceAccount
  name: rosa-namespace-provisioner
  namespace: default 