apiVersion: apps/v1
kind: Deployment
metadata:
  name: rosa-namespace-provisioner
  labels:
    app: rosa-namespace-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rosa-namespace-provisioner
  template:
    metadata:
      labels:
        app: rosa-namespace-provisioner
    spec:
      serviceAccountName: rosa-namespace-provisioner
      containers:
      - name: controller
        image: rosa-namespace-provisioner:latest
        imagePullPolicy: Always
        args:
        - --v=2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000 