apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rosa-namespace-provisioner
rules:
- apiGroups: ["user.openshift.io"]
  resources: ["groups"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["project.openshift.io"]
  resources: ["projects"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rosa-namespace-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rosa-namespace-provisioner
subjects:
- kind: ServiceAccount
  name: rosa-namespace-provisioner 