name: PR Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      
    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.1.0
      with:
        go-version: '1.24'
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
        
    - name: Cache Go modules
      uses: actions/cache@6849a6489cac3c661b3c7e0322f4ad8890e3e52e # v4.1.2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Download dependencies
      run: go mod download
      
    - name: Run tests
      run: make test
      
    - name: Run Go vet
      run: go vet ./...
      
    - name: Build application
      run: make build
      
    - name: Build container image
      run: CONTAINER_RUNTIME=docker make docker-build
      
    - name: Verify container image
      run: |
        docker images | grep rosa-namespace-provisioner
        echo "Container image built successfully" 