name: Build and Publish

on:
  push:
    branches: [ main ]

env:
  REGISTRY: quay.io
  IMAGE_NAME: redhat-ai-dev/rosa-namespace-provisioner

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Download dependencies
      run: go mod download
      
    - name: Run tests
      run: make test
      
    - name: Run Go vet
      run: go vet ./...
      
    - name: Build application
      run: make build
      
    - name: Set up container metadata
      id: meta
      run: |
        echo "image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT
        echo "commit_sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        echo "timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        
    - name: Build and push container images
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          ${{ steps.meta.outputs.image }}:latest
          ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.commit_sha }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.created=${{ steps.meta.outputs.timestamp }}
        
    - name: Output image details
      run: |
        echo "🚀 Successfully published container images:"
        echo "📦 ${{ steps.meta.outputs.image }}:latest"
        echo "📦 ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.commit_sha }}"
        echo "🔗 Image registry: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" 